- ext/vernier/vernier.cc
Unnamed semaphores have been deprecated on macOS, lets use GCD instead
This seems to fix the compiler warnings, and appears to work.  Though I'm not clear if it's safe to mix GCD semaphores with pthreads. 🤷‍♀️
> Use Apple specific semaphores

- ext/vernier/vernier.cc
For some reason, we're seeing threads on macOS Ruby 3.3 transition from STOPPED to SUSPENDED.  If a thread becomes STOPPED, we don't want to try sampling it because it's possible (probably) that the thread is dead.
> Threads should never transition from stopped to something else

- lib/vernier/output/firefox.rb
I shouldn't have hardcoded the category for GC, so this patch saves off the GC category and then we just ask for the id when generating the profile.
I left the JIT category even though we can't use it yet.
> Stop hardcoding the category for GC

- lib/vernier/output/firefox.rb
Frame implementations are how the Gecko profiler differentiates native / JIT / Ruby frames
> Add frame implementations

- ext/vernier/vernier.cc
- lib/vernier/marker.rb
- test/test_time_collector.rb
I want to see thread status as intervals in the marker chart.  This is a WIP to do it.
> Thread Intervals

- ext/vernier/vernier.cc
- test/test_time_collector.rb
- Added a custom SleepUntil function that is more accurate to avoid any timer resolutions delays introduced by the system.
- Added a TEST_SLEEP_SCALE environment variable that will slow down specs for slower systems
> Hyper Accurate Timing for Slow Systems

- README.md
Remove empty link from README!
> Remove empty link from README

- examples/rails.rb
- exe/vernier
- ext/vernier/vernier.cc
- lib/vernier.rb
- lib/vernier/autorun.rb
- lib/vernier/output/firefox.rb
- lib/vernier/result.rb
- test/test_allocations.rb
https://www.youtube.com/watch?v=ELa9vgPA1B4
```
Vernier.trace(allocation_sample_rate: 100) do
...
```
```
vernier run --allocation-sample-rate=100 -- ...
```
> Allocation Tracing

- lib/vernier.rb
- test/test_time_collector.rb
Closes https://github.com/jhawthorn/vernier/issues/58
> Add `Vernier#start_profile` and `Vernier#stop_profile`

- lib/vernier/result.rb
Fixes https://github.com/jhawthorn/vernier/issues/70
> Use binwrite to fix encoding problems when trying to write a gzip

- ext/vernier/vernier.cc
- lib/vernier/collector.rb
- lib/vernier/output/firefox.rb
- test/test_retained_memory.rb
- test/test_time_collector.rb
Closes https://github.com/jhawthorn/vernier/issues/30
> Include collector options in result object

- ext/vernier/vernier.cc
- test/integration_test.rb
- test/test_allocations.rb
> Fix crash when sampling allocations during boot

- .github/workflows/sentry.yml
@solnic I wanted to add this so that we have some degree of testing that we keep the API compatible with Sentry's integration.
Let me know if there's anything else we can do to accommodate sentry's usage ❤️
> Sentry integration test

- ext/vernier/vernier.cc
- lib/vernier/output/firefox.rb
- test/output/test_firefox.rb
> Improve handling of non-ascii method names

- ext/vernier/extconf.rb
- ext/vernier/memory.cc
- ext/vernier/timestamp.hh
- ext/vernier/vernier.cc
- ext/vernier/vernier.hh
- lib/vernier/collector.rb
- lib/vernier/hooks.rb
- lib/vernier/hooks/memory_usage.rb
- lib/vernier/output/firefox.rb
- test/test_memory_tracker.rb
> Add a memory usage profiler (w/ C background thread)

- README.md
Addresses https://github.com/jhawthorn/vernier/issues/108#issuecomment-2513707958
> Specify OS requirement in README

- README.md
- lib/vernier/middleware.rb
Closes https://github.com/jhawthorn/vernier/issues/127
> Mention `Vernier::Middleware` in README

- README.md
Follow-up to https://github.com/jhawthorn/vernier/pull/130
> Mention middleware options in README

- README.md
> Better README options table formatting (take 2)

- ext/vernier/vernier.cc
> Rename FrameInfo -> FuncInfo

- README.md
- lib/vernier/autorun.rb
- lib/vernier/collector.rb
- lib/vernier/output/firefox.rb
- test/test_time_collector.rb
Closes https://github.com/jhawthorn/vernier/issues/142
> Add metadata option to collector

- README.md
Closes https://github.com/jhawthorn/vernier/issues/138
> Document hooks
