test/test_retained_memory.rb

Instead of `Expected false to be truthy`, we'll see messages like `Expected 792 to be < 320`

Use assert_operator for better assertion failures

---

ext/vernier/vernier.cc
lib/vernier/output/firefox.rb
test/test_time_collector.rb

This PR has two commits:
1. Record the boot thread state: we should initialize threads with the thread that started Vernier
2. Record GC events
I configured this to use Tracepoint events.  The downside is that it looks like any GC related tracepoint events will cause the GC to do slowpath allocations.
In the allocator, [this conditional](https://github.com/tenderlove/ruby/blob/b41fc9b9a4ad2043a9fabce15814eade9b252569/gc.c#L2810) determines if we should do a slowpath allocation.  That macro simply [looks at `has_hook` on objspace](https://github.com/tenderlove/ruby/blob/b41fc9b9a4ad2043a9fabce15814eade9b252569/gc.c#L2449).  It looks like that boolean will get [set to true for any GC event](https://github.com/tenderlove/ruby/blob/b41fc9b9a4ad2043a9fabce15814eade9b252569/gc.c#L2399-L2405), …

Log GC events and eagerly initialize initial thread

---

ext/vernier/vernier.cc
lib/vernier.rb
lib/vernier/collector.rb
lib/vernier/marker.rb
lib/vernier/output/firefox.rb
test/output/test_firefox.rb
test/test_time_collector.rb

This PR refactors the way we handle markers.  My main goal was to make the profiler instance responsible for reconciling GC markers.  Now we can add an "add marker" interface to the collector so that users can add custom markers to their profiles.
One change of note is that I moved the `stop` method to Ruby, and change the C++ implementation to a private method called `finish`.
I also exposed the marker type enum in Ruby and pulled the marker name string literals in to Ruby as well.
I added an `initialize` method to the collector object so we can initialize a Ruby array for custom markers (right now it just keeps the profile type as an ivar).

Refactor marker handling

---

ext/vernier/vernier.cc
lib/vernier/collector.rb
lib/vernier/marker.rb

This PR teaches the profiler about different marker types including interval markers.  The profiler will now natively record an interval type for GC pauses.  This way we can reduce the post processing required when producing a profile.

Teach the profiler about interval markers

---

lib/vernier/marker.rb
lib/vernier/output/firefox.rb

Help clean up the marker chart so that Thread events are separate from generic events

Put thread markers in their own category

---

ext/vernier/vernier.cc

We know the size, so we may as well pre-allocate the Ruby array size

Initialize marker list array size

---

bin/vernier
exe/vernier
lib/vernier/autorun.rb

Based heavily on the stackprof CLI + @tenderlove's signal-based toggling
```
$ bin/vernier --help
Usage: vernier run [FLAGS] -- COMMAND
FLAGS:
--output [FILENAME]          output filename
--interval [MICROSECONDS]    sampling interval (default 500)
--signal [NAME]              specify a signal to start and stop the profiler
--start-paused               don't automatically start the profiler
$ bin/vernier run --output profile.json --interval=1000 -- ruby -e 'sleep 1'
starting profiler with interval 1000
profile written to profile.json
```

Add vernier CLI

---

ext/vernier/vernier.cc

We used to only sample running threads because started threads didn't have the full VM set yet.  In PR #18, we changed the event we listen for, and when that event is fired it should be safe to collect samples. This patch makes "started" threads considered as "running" so we'll get those samples.

Started threads should be considered "running"

---

lib/vernier/collector.rb
lib/vernier/output/firefox.rb
test/output/test_firefox.rb

If we use the UserTiming marker type, then the user timing bar can optionally be displayed on the stack chart
Here's a sample usage:
```ruby
require "vernier"
def sieve max
sieve = []
for i in 2 .. max
sieve[i] = i
end
for i in 2 .. Math.sqrt(max)
next unless sieve[i]
(i*i).step(max, i) do |j|
sieve[j] = nil
end
end
sieve.compact
end
Vernier.trace(out: "time_profile.json") { |v|
2.times.map {
Thread.new {
3.times do |i|
GC.start
v.record_interval "sieve", "Iteration #{i}" do
sleep 0.1
v.record_interval "sieve2", "Iteration #{i}" do
sieve(5000000)
end
end
end
}
}.map(&:join)
}
```

Make `record_interval` use "UserTiming" marker

---

ext/vernier/vernier.cc

If the GVL is immediately available, avoid emitting a 0-length marker.
**Before:**
**After:**
(which makes me wonder if we should skip 0-length suspended/running as well)

Skip emitting empty STALLED markers

---

lib/vernier.rb
test/test_time_collector.rb

I am not sure of the validity of the resulting trace, but I would like this to work because I would love visibility into a failing test case that's shaped like this:
```ruby
Vernier.trace(out: "tmp/trace.json") do
wrap_something do |intermediate_result|
assert intermediate_result # <- this raises
end
end
```

Allow `Vernier.trace` to write output file even when exception is raised within block

---

lib/vernier/output/firefox.rb

I ran into this failure when trying this tool out using `Ruby 3.2.2`.
```ruby
/Users/[redacted]/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/warning-1.3.0/lib/warning.rb:260:in `warn': /Users/[redacted]/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/vernier-0.3.0/lib/vernier/output/firefox.rb:240: warning: assigned but unused variable - size (RuntimeError)
from /Users/[redacted]/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/vernier-0.3.0/lib/vernier.rb:7:in `require_relative'
from /Users/[redacted]/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/vernier-0.3.0/lib/vernier.rb:7:in `<top (required)>'
from <internal:/Users/[redacted]/.rbenv/versions/3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
from <internal:/Users/[redacted]/.rbenv/versions/3.2.2/lib/ruby/3.2.0/ …
```

Remove unused var and redundant raise in `Vernier::Output::Firefox`

---

test/test_time_collector.rb

- Everyone gets generous epsilons, because tests based on time can be a bit flakey
- test_nested_collections is now influenced by TEST_SLEEP_SCALE
We should document TEST_SLEEP_SCALE somewhere.

Update Tests to be a little more Resilient

---

vernier.gemspec

3.2.0 has a bug that cause `rb_profile_frames` to not be async signal safe: https://github.com/ruby/ruby/pull/7116
It has been backported in 3.2.1, so might as well prevent the installation of the gem.
Fix: https://github.com/jhawthorn/vernier/issues/42
cc @m-zielinski, @jhawthorn

Require Ruby 3.2.1+

---

README.md

This came up in the Rails Performance Slack and seemed useful to draw attention to as a benefit.

Explain difference between Flame Graph and Stack Chart

---

README.md

This change adds the minimum Ruby version requirement so that users do not spend time wondering why the Vernier traces are malformed and fail to render in the profile viewers ☺️

Update README to emphasize Ruby version requirement

---

ext/vernier/vernier.cc

TLDR; Otherwise you can have exception like :
```
Assertion Failed: vernier.cc:857:set_state:state == State::RUNNING || state == State::STARTED
```
---
I wanted to plug Vernier to the [benchmark](https://github.com/speedshop/threadbench) mentioned here https://github.com/rails/rails/issues/50450. While trying to plug it, I was stop by an exception from Vernier. I modified the code to permit this handling of state and I was able to [get a result](https://share.firefox.dev/3vSXggu).
It is maybe a mistake from when I tried to setup Vernier on this project. It [can be seen here](https://github.com/speedshop/threadbench/compare/main...benoittgt:threadbench:3.3?expand=1#diff-5fe74a7aca8668f86d1251d17e23b3ac9c55504d8d78698a8168a9cae87b350c).
I am not sure we want to permit this, or instead raise …

Permit thread state SUSPENDED to go to STOPPED

---

examples/rails.rb
ext/vernier/vernier.cc
lib/vernier.rb
lib/vernier/collector.rb
lib/vernier/hooks.rb
lib/vernier/hooks/active_support.rb
lib/vernier/output/firefox.rb
lib/vernier/result.rb

Add Hook for ActiveSupport::Notifications

---

lib/vernier.rb
lib/vernier/collector.rb

Adresses:
- https://github.com/jhawthorn/vernier/pull/59#discussion_r1546944913
- https://github.com/jhawthorn/vernier/pull/59#discussion_r1546945557
Another change in behaviour worth mentioning is that `GC.start` now runs after [this initialisation](https://github.com/jhawthorn/vernier/blob/b608919298e2c67f16e137b0cdd23947812f40e3/ext/vernier/vernier.cc#L1714-L1739), whereas before it preceded it.

Move `:out` and `:gc` to collector

---

Gemfile
examples/measure_overhead.rb
ext/vernier/vernier.cc
lib/vernier.rb
lib/vernier/collector.rb
lib/vernier/output/firefox.rb
lib/vernier/result.rb
lib/vernier/stack_table.rb
test/firefox_test_helpers.rb
test/test_helper.rb
test/test_stack_table.rb

StackTable exposes Vernier's (previously internal) method of collecting stacks and frames without making Ruby allocations and returns a single integer representing a unique stack.
```
stack_table = Vernier::StackTable.new
stack_table.current_stack #=> 12
stack_table.current_stack #=> 13
```
This can later be decoded
```
stack_table.backtrace(12)
#=> ["test.rb:5:in 'foo'",
```
The first use of this can be collecting stack indexes which are compatible with the output of Vernier's collectors (ex. to add them to markers). The second is performance.
This is 2-3x faster than using `caller_locations`, however the biggest gains would be when additional processing is done on the stack in Ruby (ex. filtering or reformatting) which can be avoided because stacks and frames are de-duplicated.
```
ruby …
```

Expose StackTable to Ruby

---

lib/vernier.rb

Mostly a cosmetic change. #61 moved the options to the collector itself, a benefit of that is not having to update all the profile method APIs every time a new option is added.
This ensures `trace_contained` is consistent with the rest of these methods.

Make `trace_retained` API consistent with `profile`

---

ext/vernier/vernier.cc

In order to get the current thread id on FreeBSD, we can use the non-portable `pthread_getthreadid_np()` function.
Test suite pass:
```sh-session
romain@zappy ~/Projects/vernier % bundle exec rake                                                                                             
mkdir -p tmp/amd64-freebsd14/vernier/3.2.3
cd tmp/amd64-freebsd14/vernier/3.2.3
/usr/local/bin/ruby32 -I. ../../../../ext/vernier/extconf.rb
checking for ruby/thread.h... yes
checking for rb_internal_thread_event_data_t.thread in ruby/thread.h... no
checking for rb_profile_thread_frames() in ruby/debug.h... no
checking for pthread_setname_np()... yes
creating Makefile
cd -
cd tmp/amd64-freebsd14/vernier/3.2.3
/usr/local/bin/gmake
compiling ../../../../ext/vernier/vernier.cc
linking shared-object …
```

Add support for FreeBSD

---

lib/vernier/middleware.rb

While integrating this into an app, I noticed these are accessed as symbols, which I'm pretty sure won't work.
A few lines up from the diff in this PR, the `request.GET.has_key?("vernier")` is accessed as a string, so I'm pretty sure this is the right way to do it.

Middleware: access Rack GET params as strings not symbols

---

ext/vernier/vernier.cc
lib/vernier/output/firefox.rb
test/firefox_test_helpers.rb
test/output/test_firefox.rb

Closes https://github.com/jhawthorn/vernier/issues/56
Related to https://github.com/jhawthorn/vernier/pull/75
Ensures that on profile load, no threads are filtered out i.e. [`initialVisibleThreads`](https://github.com/firefox-devtools/profiler/blob/245b1a400c5c368ccc13641d0335398bafa0e870/src/types/profile.js#L909-L912) contains all threads, and that the thread in which the profiler was started is the pre-selected thread i.e. it's the one and only thread in [`initialSelectedThreads`](https://github.com/firefox-devtools/profiler/blob/245b1a400c5c368ccc13641d0335398bafa0e870/src/types/profile.js#L913-L916).
<details>
<summary>Manual testing</summary>
```ruby
Vernier.profile(out: "output_main.json") do
10.times.map do |i|
Thread.new do
Thread.current.name = "Spawned #{i}"
sleep 0.01
end …
```

Show all threads and pre-select profile start thread by default

---

exe/vernier

Previous output:
```
$ vernier -v
vernier: version unknown
```
Optparser generates a version swtich by default, even if it doesn't appear in the help output. Tested by building and installing the gem locally.

Fix output of `vernier --version`

---

lib/vernier/result.rb
test/test_retained_memory.rb

Fixes https://github.com/jhawthorn/vernier/issues/84

Fix undefined method `Vernier::Result#frame_line_idx`

---

ext/vernier/vernier.cc
test/test_helper.rb
test/test_time_collector.rb

Fixes https://github.com/jhawthorn/vernier/issues/85
This works around a bug where we get an empty stack on suspend. In the future we should better support having an empty stack.
This fixes an issue where we would record a `-1` sample and then when creating the firefox-compatible output would end up with a null in the frame list and make the resulting file error on load.

Avoid recording -1 sentinel in profile

---

exe/vernier

This adds a "view" command to the Vernier CLI. Right now, it just prints a table of the top 20 most sampled leaf methods. This is equivalent to viewing the inverted call graph in the Firefox profile viewer.
Here's what it looks like:
```
$ ruby -I lib exe/vernier view ~/git/profile20240814-33519-taluco.vernier.json
+---------+------+------------------------------------------------------------+
| Samples | %    |                                                            |
+---------+------+------------------------------------------------------------+
| 10639   | 60.8 | Thread::Queue#pop                                          |
| 3036    | 17.4 | Thread#value                                               |
| 738     | 4.2  | Thread#join                                                |
| …
```

Add a simple text viewer

---

README.md
examples/measure_overhead.rb
examples/rails.rb
examples/threaded_http_requests.rb
exe/vernier
ext/vernier/vernier.cc
lib/vernier/autorun.rb
lib/vernier/middleware.rb
test/integration_test.rb
test/output/test_firefox.rb
test/test_allocations.rb
test/test_retained_memory.rb
test/test_time_collector.rb

Closes https://github.com/jhawthorn/vernier/issues/91
Renames the CLI flag from `--allocation_sample_rate` to `--allocation-interval` (hyphen for consistency with `--start-paused`, also pretty standard).
Renames the option kwarg from `allocation_sample_rate` to `allocation_interval`. Also renamed vars to match.

Rename `allocation_sample_rate` to `allocation_interval`

---

ext/vernier/vernier.cc
test/test_helper.rb

Reproduces: https://github.com/jhawthorn/vernier/issues/100
cc @jhawthorn

Enable GC.auto_compact in test suite

---

.gitignore
examples/fiber_stalls.rb
ext/vernier/vernier.cc
lib/vernier/collector.rb
lib/vernier/marker.rb
lib/vernier/output/firefox.rb
lib/vernier/result.rb
test/test_active_support.rb
test/test_time_collector.rb

Fiber Running and Fiber Switch events give us information about what Fibers in the system are doing.  The Fiber Running span in the marker chart allow us to easily select work that a particular Fiber is doing, where the Fiber Switch event allows us to identify why a Fiber changed.
Here is a sample program we'll profile with Vernier:
```ruby
require "async"
require "async/queue"
def measure
x = Process.clock_gettime(Process::CLOCK_MONOTONIC)
yield
Process.clock_gettime(Process::CLOCK_MONOTONIC) - x
end
def fib(n)
if n < 2
n
else
fib(n-2) + fib(n-1)
end
end
fib_i = 50.times.find { |i| measure { fib(i) } >= 0.05 }
sleep_i = measure { fib(fib_i) }
Async {
latch = Async::Queue.new
workers = [
Async {
latch.pop # block until ready to measure
100.times {
sleep(sleep_i)
}
},
Async {
latch.pop # …
```

Add Fiber Running / Fiber Switch events to the marker chart

---

ext/vernier/extconf.rb
ext/vernier/memory.cc
ext/vernier/periodic_thread.hh
ext/vernier/signal_safe_semaphore.hh
ext/vernier/timestamp.hh
ext/vernier/vernier.cc
test/test_allocations.rb
test/test_time_collector.rb

I want to use the same "PeriodicThread" implementation that came from the recent memory profiling for the sampling timer as well.
This allows us to cancel the thread more quickly (previously we had to wait for the timer to expire to stop the sampling thread) and I want to build the ability to "pause" profiling on top of this, which I then want to use to fix the issues we have when forking.

Use PeriodicThread for sampling

---

test/test_retained_memory.rb

Example failure: https://github.com/jhawthorn/vernier/actions/runs/12829459612/job/35803700089#step:4:333
Ref:https://github.com/ruby/ruby/commit/073c4e1cc712064e626914fa4a5a8061f903a637

Fix failing retained memory test on head

---

lib/vernier/output/file_listing.rb

This PR separates `Vernier::Output::FileListing::SamplesByLocation#output` into `samples_by_file` for parsing the samples and `output` for making the actual output string, to prepare for adding more options for customizing the file listing display.

Separate parsing samples_by_file from output 

---

lib/vernier/output/firefox.rb
test/firefox_test_helpers.rb

Closes https://github.com/jhawthorn/vernier/issues/128
I wonder why we set the frame category but not the subcategory here 🤔 ~Anyway, I've kept it as `nil` to maintain behaviour while ensuring we conform to the expected Firefox type.~ See https://github.com/jhawthorn/vernier/pull/129#issuecomment-2661156921.

Ensure Firefox frame table subcategory fields are always included

---

.github/workflows/main.yml
test/test_stack_table.rb

Since many ruby core methods are being re-written in ruby for when YJIT is enabled, I think it might be a good idea to run a build for the latest release and head with it enabled to catch any behavioural changes e.g. caller location entries like in [the test that fails on this branch](https://github.com/jhawthorn/vernier/actions/runs/14006305734/job/39220608434?pr=135#step:4:36).

Add CI build for YJIT

---

lib/vernier/output/firefox.rb

Fix: https://github.com/jhawthorn/vernier/issues/147
It's deprecated for JSON 3.0. It never was significantly faster than `JSON.generate` it only disabled depth checks.

Avoid `JSON.fast_generate`

---

lib/vernier/output/file_listing.rb

The util one emits a warning on Ruby 3.5
https://bugs.ruby-lang.org/issues/21258
There's one test failure because of https://bugs.ruby-lang.org/issues/21254 (inlining Class#new) on Ruby 3.5 which is unrelated.

Require `cgi/esacpe` instead of `cgi/util`

---

exe/vernier
lib/vernier/autorun.rb

I tried to run `vernier` with Ruby 3.4, but I got the following warning.
```bash
$ vernier run -- bundle exec ruby -ve 'sleep 1'
/home/yyagi/.rbenv/versions/3.4.2/lib/ruby/gems/3.4.0/gems/vernier-1.7.1/lib/vernier/autorun.rb:3: warning: base64 was loaded from the standard library, but is not part of the default gems starting from Ruby 3.4.0.
You can add base64 to your Gemfile or gemspec to silence this warning.
```
As the warning describes, `vernier` uses `base64`, but it's not added to the dependency.
`vernier` uses `base64` only in two places. So I changed those not using `base64` instead of adding a dependency.
Ref:
* https://github.com/ruby/base64/blob/cd65c103c571f8451fec796e5685db9a3047128d/lib/base64.rb#L219-L221
* https://github.com/ruby/base64/blob/cd65c103c571f8451fec796e5685db9a …

Drop `base64` dependency

---

lib/vernier/middleware.rb
lib/vernier/result.rb

In preparation for other output formats, I'd like to rename `to_gecko` to `to_firefox` so it's a little more consistent with the intended use (Firefox Profiler being the target). Gecko might be a little esoteric.
I'm aliasing `to_gecko` so it's not a breaking change, but happy to remove that if we want to remove it, or add a more formal deprecation if we feel we need it

refactor: rename to_gecko to to_firefox

---

exe/vernier
lib/vernier/output/top.rb
test/output/test_top.rb

We're supposed to be limiting the number of rows in the output to a default of 20, but it seems like we were just throwing the limit away 😅
This commit respects the row limit in the CLI output

Fix the row limit in the CLI profile output
